/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.khalibre.student.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the StudentEntry service. Represents a row in the &quot;STUDENT_StudentEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.khalibre.student.model.impl.StudentEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.khalibre.student.model.impl.StudentEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see StudentEntry
 * @generated
 */
@ProviderType
public interface StudentEntryModel extends BaseModel<StudentEntry> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a student entry model instance should use the {@link StudentEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this student entry.
	 *
	 * @return the primary key of this student entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this student entry.
	 *
	 * @param primaryKey the primary key of this student entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this student entry.
	 *
	 * @return the uuid of this student entry
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this student entry.
	 *
	 * @param uuid the uuid of this student entry
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the student entry ID of this student entry.
	 *
	 * @return the student entry ID of this student entry
	 */
	public long getStudentEntryId();

	/**
	 * Sets the student entry ID of this student entry.
	 *
	 * @param studentEntryId the student entry ID of this student entry
	 */
	public void setStudentEntryId(long studentEntryId);

	/**
	 * Returns the student entry name of this student entry.
	 *
	 * @return the student entry name of this student entry
	 */
	@AutoEscape
	public String getStudentEntryName();

	/**
	 * Sets the student entry name of this student entry.
	 *
	 * @param studentEntryName the student entry name of this student entry
	 */
	public void setStudentEntryName(String studentEntryName);

	/**
	 * Returns the student entry gender of this student entry.
	 *
	 * @return the student entry gender of this student entry
	 */
	@AutoEscape
	public String getStudentEntryGender();

	/**
	 * Sets the student entry gender of this student entry.
	 *
	 * @param studentEntryGender the student entry gender of this student entry
	 */
	public void setStudentEntryGender(String studentEntryGender);

	/**
	 * Returns the student entry age of this student entry.
	 *
	 * @return the student entry age of this student entry
	 */
	public int getStudentEntryAge();

	/**
	 * Sets the student entry age of this student entry.
	 *
	 * @param studentEntryAge the student entry age of this student entry
	 */
	public void setStudentEntryAge(int studentEntryAge);

}